<?php
$xmlstr= <<<XML
<?xml version="1.0" encoding="utf-8"?>
<utilisateurs>
    <utilisateur>
        <nom>Girard</nom> 
        <prenom>Daniel</prenom>
        <pseudo>dagira</pseudo>
        <date>28/05/1988</date> 
        <mdp>dagira88</mdp>
        <mail>sikara57@gmail.com</mail>
    </utilisateur>
    <utilisateur>
        <nom></nom>
        <prenom></prenom>
        <pseudo></pseudo>
        <date></date>
        <mdp></mdp>
        <mail></mail>
    </utilisateur>
    <utilisateur>
        <nom></nom>
        <prenom></prenom>
        <pseudo></pseudo>
        <date></date>
        <mdp></mdp>
        <mail></mail>
    </utilisateur>
    <utilisateur>
        <nom></nom>
        <prenom></prenom>
        <pseudo></pseudo>
        <date></date>
        <mdp></mdp>
        <mail></mail>
    </utilisateur>
    <utilisateur>
        <nom></nom>
        <prenom></prenom>
        <pseudo></pseudo>
        <date></date>
        <mdp></mdp>
        <mail></mail>
    </utilisateur>
    <utilisateur>
        <nom></nom>
        <prenom></prenom>
        <pseudo></pseudo>
        <date></date>
        <mdp></mdp>
        <mail></mail>
    </utilisateur>
    <utilisateur>
        <nom></nom>
        <prenom></prenom>
        <pseudo></pseudo>
        <date></date>
        <mdp></mdp>
        <mail></mail>
    </utilisateur>
    <utilisateur>
        <nom></nom>
        <prenom></prenom>
        <pseudo></pseudo>
        <date></date>
        <mdp></mdp>
        <mail></mail>
    </utilisateur>
    <utilisateur>
        <nom></nom>
        <prenom></prenom>
        <pseudo></pseudo>
        <date></date>
        <mdp></mdp>
        <mail></mail>
    </utilisateur>
    <utilisateur>
        <nom></nom>
        <prenom></prenom>
        <pseudo></pseudo>
        <date></date>
        <mdp></mdp>
        <mail></mail>
    </utilisateur>
    <utilisateur>
        <nom></nom>
        <prenom></prenom>
        <pseudo></pseudo>
        <date></date>
        <mdp></mdp>
        <mail></mail>
    </utilisateur>
    <utilisateur>
        <nom></nom>
        <prenom></prenom>
        <pseudo></pseudo>
        <date></date>
        <mdp></mdp>
        <mail></mail>
    </utilisateur>
    <utilisateur>
        <nom></nom>
        <prenom></prenom>
        <pseudo></pseudo>
        <date></date>
        <mdp></mdp>
        <mail></mail>
    </utilisateur>
</utilisateurs>
XML;
?>